[package]
name = "exogress-assistant"
version = "0.1.0"
authors = ["Exogress Team <team@exogress.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.21", features = ["tcp", "time", "signal", "fs"] }
futures = "0.3.5"
serde_json = "1.0.48"
serde = { version = "1.0.105", features = ["derive"] }
thiserror = "1.0.13"
sentry = "0.19.0"
rand = { version = "0.7", features = ["small_rng"] }
stop-handle = "0.1"
pin-project = "0.4"
redis = {version = "0.17.0", default-features = false, features = ["tokio-rt-core", "tokio-comp", "connection-manager"]}
clap = "2.33.3"
warp = "=0.2.5"
anyhow = "1.0.31"
shadow-clone = "1.2.1"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2.4"
hashbrown = { version = "0.8", features = ["serde"] }
chrono = { version = "0.4.11", features = ["serde"] }
clickhouse-rs = { git = "https://github.com/suharev7/clickhouse-rs.git", branch = "async-await" }
chrono-tz = "0.5.3"

exogress-server-common = { path = "../common" }
exogress-common-utils = { path = "../../deps/exogress/crates/common-utils" }
exogress-entities = { path = "../../deps/exogress/crates/entities" }
