[package]
name = "exogress-signaler"
version = "0.1.0"
authors = ["Exogress Team <team@exogress.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.21", features = ["tcp", "time", "signal"] }
futures = "0.3.5"
serde_json = "1.0.48"
serde = { version = "1.0.105", features = ["derive"] }
serde_derive = "1.0.25"
thiserror = "1.0.13"
sentry = "0.19.0"
derive_builder = "0.9.0"
trust-dns-resolver = "0.19.5"
rand = { version = "0.7", features = ["small_rng"] }
stop-handle = "0.1"
pin-project = "0.4"
http = "0.2"
hostname = "0.3.1"
byteorder = "1.3.4"
smartstring = { version  = "0.2.3", features = ["serde"] }
redis = {version = "0.17.0", default-features = false, features = ["tokio-rt-core", "tokio-comp", "connection-manager"]}
mimalloc = "0.1.19"
clap = "3.0.0-beta.1"
reqwest = {version ="0.10.6", features = ["rustls-tls", "json", "trust-dns"] }
lazy_static = "1.4.0"
warp = "=0.2.4"
anyhow = "1.0.31"
prometheus = "0.9.0"
shadow-clone = "1.2.1"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2.4"

exogress-server-common = { path = "../common" }
exogress-common-utils = { path = "../../deps/exogress/crates/common-utils" }
exogress-entities = { path = "../../deps/exogress/crates/entities" }
exogress-config-core = { path = "../../deps/exogress/crates/config-core" }
exogress-client-core = { path = "../../deps/exogress/crates/client-core" }
exogress-signaling = { path = "../../deps/exogress/crates/signaling" }
