[package]
name = "exogress-server-common"
version = "0.1.0"
authors = ["Gleb Pomykalov <gleb@lancastr.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
sentry = { version = "0.19.0", features = ["backtrace", "panic", "anyhow"] }
tracing = "0.1"
url = "2.1.1"
