[package]
name = "exogress-server-common"
version = "0.1.0"
authors = ["Gleb Pomykalov <gleb@lancastr.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
sentry = { version = "0.19.0", features = ["backtrace", "panic", "anyhow"] }
tracing = "0.1"
url = "2.1.1"
serde = { version = "1.0.105", features = ["derive"] }
chrono = { version = "0.4.15", features = ["serde"] }
thiserror = "1.0.20"
serde_json = "1.0.48"
chrono-tz = "0.5.3"
http-serde = "1.0.1"
http = "0.2.1"

exogress-entities = { path = "../../deps/exogress/crates/entities" }
exogress-config-core = { path = "../../deps/exogress/crates/config-core", version = "0.1" }
