[workspace]
members = [
 "common",
 "gateway",
 "signaler",
 "assistant",
 "director",
]

[profile.release]
lto = true
#debug = true

#[patch.crates-io]
#hyper = { path = '../deps/hyper' }
#warp = { path = "../deps/warp" }
