[workspace]
members = [
 "common",
 "api",
 "gateway",
 "dns",
 "signaler",
 "assistant",
 "director",
 "transformer",
 "commiter",
]

[profile.release]
lto = true

[profile.dev]
split-debuginfo = "unpacked"