[workspace]
members = [
 "common",
 "gateway",
 "signaler",
 "assistant",
]

[profile.release]
lto = true
#debug = true

[patch.crates-io]
hyper = { path = '../deps/hyper' }
warp = { path = "../deps/warp" }