name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  IMAGE: servers
  IMAGE_SIGNALER: quay.io/exogress/signaler
  IMAGE_GATEWAY: quay.io/exogress/gateway
  IMAGE_ASSISTANT: quay.io/exogress/assistant
  IMAGE_DIRECTOR: quay.io/exogress/director
  IMAGE_POSTFIX: ""
  TAG: dev

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          crates/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run cargo test
      run: cargo test
      working-directory: ./crates

  build-images:
    name: Build Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get branch name
#      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

    - name: Debug
      run: echo ${{ env.BRANCH_NAME }}

    - name: Set image postfix
      run: echo "::set-env name=IMAGE_POSTFIX::-develop"
      if: env.BRANCH_NAME == 'refs-pull-1-merge'

    - name: Login to quay.io
      uses: docker/login-action@v1
      if: env.BRANCH_NAME == 'refs-pull-1-merge' || env.BRANCH_NAME == 'master'
      with:
        registry: quay.io
        username: exogress+publisher
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build
      if: env.BRANCH_NAME == 'refs-pull-1-merge' || env.BRANCH_NAME == 'master'
      run:
        docker build --pull --target=builder -t ${IMAGE}:${TAG} .

    - name: Build signaler
      if: env.BRANCH_NAME == 'refs-pull-1-merge' || env.BRANCH_NAME == 'master'
      run:
        docker build --pull --target=signaler -t ${IMAGE_SIGNALER}${IMAGE_POSTFIX}:${TAG} .

    - name: Build director
      if: env.BRANCH_NAME == 'refs-pull-1-merge' || env.BRANCH_NAME == 'master'
      run:
        docker build --pull --target=director -t ${IMAGE_DIRECTOR}${IMAGE_POSTFIX}:${TAG} .

    - name: Build gateway
      if: env.BRANCH_NAME == 'refs-pull-1-merge' || env.BRANCH_NAME == 'master'
      run:
        docker build --pull --target=gateway -t ${IMAGE_GATEWAY}${IMAGE_POSTFIX}:${TAG} .

    - name: Build assistant
      if: env.BRANCH_NAME == 'refs-pull-1-merge' || env.BRANCH_NAME == 'master'
      run:
        docker build --pull --target=assistant -t ${IMAGE_ASSISTANT}${IMAGE_POSTFIX}:${TAG} .

