name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  IMAGE: servers
  IMAGE_SIGNALER: signaler
  IMAGE_GATEWAY: gateway
  IMAGE_ASSISTANT: assistant
  IMAGE_DIRECTOR: director
  TAG: dev

jobs:
  build-images:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run:
        docker build --pull --target=builder -t ${IMAGE}:${TAG} .
