name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  IMAGE: servers
  IMAGE_SIGNALER: signaler
  IMAGE_GATEWAY: gateway
  IMAGE_ASSISTANT: assistant
  IMAGE_DIRECTOR: director
  TAG: dev

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          crates/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run cargo test
      run: cargo test
      working-directory: ./crates

#  build-images:
#    name: Build
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#      with:
#        submodules: true
#
#    - name: Run cargo test
#      uses: actions-rs/cargo@v1
#      with:
#        command: test
#
#    - name: Build
#      run:
#        docker build --pull --target=builder -t ${IMAGE}:${TAG} .
#
#    - name: Flush the disk cache for macOS
#      if: matrix.os == 'macos-latest'
#      run: sudo /usr/sbin/purge
