name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  IMAGE: servers
  IMAGE_SIGNALER: signaler
  IMAGE_GATEWAY: gateway
  IMAGE_ASSISTANT: assistant
  IMAGE_DIRECTOR: director
  TAG: dev

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          crates/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run cargo test
      run: cargo test
      working-directory: ./crates

  build-images:
    name: Build Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: exogress+publisher
        password: ${{ secrets.QUAY_PASSWORD }}


    - name: Build
      run:
        docker build --pull --target=builder -t ${IMAGE}:${TAG} .

    - name: Build signaler
      run:
        docker build --pull --target=signaler -t ${IMAGE_SIGNALER}:${TAG} .

    - name: Build director
      run:
        docker build --pull --target=director -t ${IMAGE_DIRECTOR}:${TAG} .

    - name: Build gateway
      run:
        docker build --pull --target=gateway -t ${IMAGE_GATEWAY}:${TAG} .

    - name: Build assistant
      run:
        docker build --pull --target=assistant -t ${IMAGE_ASSISTANT}:${TAG} .


